--- #YAML:1.0
name:                List-Rotation
version:             1.008
abstract:            Loop (Cycle, Alternate or Toggle) through a list of values via a singleton object implemented as closure.
license:             perl
author:              
    - pelagic
generated_by:        ExtUtils::MakeMaker version 6.42
distribution_type:   module
requires:     
    Memoize:                       0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
